apiVersion: apps/v1
kind: Deployment
metadata:
  name: apipeliculas-v1
  labels:
    app: apipeliculas
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apipeliculas
  template:
    metadata:
      labels:
        app: apipeliculas
        version: "1.0"
    spec:
      containers:
      - name: apipeliculas
        image: de.icr.io/svalenciaa/apipeliculas
        ports:
        - name: http-server
          containerPort: 5000     